### ISSUE TITLE
feat: StringCalculator 테스트 구현

### ISSUE THREAD

**Issue by yoownny** [yoownny/java-calculator-7#11]
## Description
StringCalculator 클래스의 기능을 검증하기 위한 테스트를 구현한다.

## Todo
- [x] 기본 구분자 사용 테스트
- [x] 커스텀 구분자 사용 테스트
- [x] 기본, 커스텀 구분자 사용 테스트
- [x] 빈 문자열 입력 처리
- [x] 연속된 구분자 처리
- [x] 공백이 있는 입력 처리
- [x] 유효하지 않은 구분자 형식 테스트
- [x] 숫자 변환 실패 테스트
- [x] 음수 입력 테스트
