### ISSUE TITLE
feat: 입력 문자열 유효성 검사

### ISSUE THREAD

**Issue by yoownny** [yoownny/java-calculator-7#3]
## Description
입력 받은 문자열의 유효성을 검사합니다.

## Todo
- [x] 입력 문자열이 비어있는지 확인
- [x] 비어있다면 `IllegalArgumentException` 발생
- [x] `IllegalArgumentException` 발생 시 "올바르지 않은 입력값입니다. 프로그램을 종료합니다." 오류 메시지 출력

**Comment by yoownny** [comment]
모든 TODO 항목이 완료되었습니다.
