### ISSUE TITLE
feat: 구분자 설정

### ISSUE THREAD

**Issue by yoownny** [yoownny/java-calculator-7#6]
## Description
기본 구분자("," 또는 ":")와 커스텀 구분자("//"와 "\n" 사이의 문자)를 사용해 문자열을 분리하여 숫자를 추출해 합계를 계산합니다.

## Todo
- [x] 기본 구분자로 전체적인 연산 실행
- [x] 커스텀 구분자 생성
- [x] 커스텀 구분자로 전체적인 연산 실행
- [x] 구분자가 연속으로 나오는 경우 설정

## ETC
입력 문자열이 빈 경우 결과 0을 반환하도록 수정한다.

**Comment by yoownny** [comment]
모든 TODO 항목이 완료되었습니다.

**Comment by yoownny** [comment]
모든 TODO 항목이 완료되었습니다.
