### ISSUE TITLE
feat: 예외 처리

### ISSUE THREAD

**Issue by yoownny** [yoownny/java-calculator-7#9]
## Description
문자열 계산기의 예외 처리 기능을 구현한다.

## Todo
- [x] 공백 처리
- [x] 유효하지 않은 구분자 형식 예외 처리
- [x] 숫자 변환 실패 예외 처리
- [x] 음수 입력 예외 처리
- [x] 기본 구분자와 커스텀 구분자 모두 사용
- [x] 특수 문자 이스케이프

## ETC
모든 예외는 `IllegalArgumentException`으로 처리한다.
develop branch를 제거하였으므로 앞으로 main 브랜치로 merge를 진행한다.

**Comment by yoownny** [comment]
모든 TODO 항목이 완료되었습니다.
